development:
  app_id: 14205
  app_key: 'b35414373fbe5cd93f3d'
  app_secret: '1754242b032fac5c3839'
  debug: true

test:
  app_id:
  app_key:
  app_secret:
  debug: true

production:
  app_id: <%= ENV['PUSHER_APP_ID'] %>
  app_key: <%= ENV['PUSHER_APP_KEY'] %>
  app_secret: <%= ENV['PUSHER_APP_SECRET'] %>
  debug: false